package in.careerscale.apps.ocms.model;

// Generated Jun 6, 2011 8:21:35 AM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CaseStatusMaster generated by hbm2java
 */
@Entity
@Table(name = "case_status_master", catalog = "ocms")
public class CaseStatusMaster implements java.io.Serializable {

	private Integer id;
	private String caseStatusName;
	private String caseStatusDescription;
	

	public CaseStatusMaster() {
	}

	public CaseStatusMaster(String caseStatusName) {
		this.caseStatusName = caseStatusName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "case_status_name", nullable = false, length = 50)
	public String getCaseStatusName() {
		return this.caseStatusName;
	}

	public void setCaseStatusName(String caseStatusName) {
		this.caseStatusName = caseStatusName;
	}

	@Column(name = "case_status_description")
	public String getCaseStatusDescription() {
		return this.caseStatusDescription;
	}

	public void setCaseStatusDescription(String caseStatusDescription) {
		this.caseStatusDescription = caseStatusDescription;
	}

}
