package in.careerscale.apps.ocms.model;

// Generated Jun 6, 2011 8:21:35 AM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CaseUser generated by hbm2java
 */
@Entity
@Table(name = "case_user", catalog = "ocms")
public class CaseUser implements java.io.Serializable {

	private CaseUserId id;
	private LoginMaster loginMaster;
	private CaseMaster caseMaster;
	private Boolean isOrg;

	public CaseUser() {
	}

	public CaseUser(CaseUserId id, LoginMaster loginMaster,
			CaseMaster caseMaster) {
		this.id = id;
		this.loginMaster = loginMaster;
		this.caseMaster = caseMaster;
	}

	public CaseUser(CaseUserId id, LoginMaster loginMaster,
			CaseMaster caseMaster, Boolean isOrg) {
		this.id = id;
		this.loginMaster = loginMaster;
		this.caseMaster = caseMaster;
		this.isOrg = isOrg;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "caseId", column = @Column(name = "case_id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
	public CaseUserId getId() {
		return this.id;
	}

	public void setId(CaseUserId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public LoginMaster getLoginMaster() {
		return this.loginMaster;
	}

	public void setLoginMaster(LoginMaster loginMaster) {
		this.loginMaster = loginMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_id", nullable = false, insertable = false, updatable = false)
	public CaseMaster getCaseMaster() {
		return this.caseMaster;
	}

	public void setCaseMaster(CaseMaster caseMaster) {
		this.caseMaster = caseMaster;
	}

	@Column(name = "is_org")
	public Boolean getIsOrg() {
		return this.isOrg;
	}

	public void setIsOrg(Boolean isOrg) {
		this.isOrg = isOrg;
	}

}
