package in.careerscale.apps.ocms.dao.model;

// Generated Jun 6, 2011 8:21:35 AM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CaseSubType generated by hbm2java
 */
@Entity
@Table(name = "case_sub_type", catalog = "ocms")
public class CaseSubType implements java.io.Serializable {

	private Integer id;
	private CaseType caseType;
	private String name;
	private String description;
	private Set<CaseMaster> caseMasters = new HashSet<CaseMaster>(0);

	public CaseSubType() {
	}

	public CaseSubType(CaseType caseType, String name) {
		this.caseType = caseType;
		this.name = name;
	}

	public CaseSubType(CaseType caseType, String name, String description,
			Set<CaseMaster> caseMasters) {
		this.caseType = caseType;
		this.name = name;
		this.description = description;
		this.caseMasters = caseMasters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_type_id", nullable = false)
	public CaseType getCaseType() {
		return this.caseType;
	}

	public void setCaseType(CaseType caseType) {
		this.caseType = caseType;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caseSubType")
	public Set<CaseMaster> getCaseMasters() {
		return this.caseMasters;
	}

	public void setCaseMasters(Set<CaseMaster> caseMasters) {
		this.caseMasters = caseMasters;
	}

}
