package in.careerscale.apps.ocms.dao.model;

// Generated Jul 7, 2013 10:49:55 AM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FundStatus generated by hbm2java
 */
@Entity
@Table(name = "fund_status", catalog = "ocms")
public class FundStatus implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set funds = new HashSet(0);

	public FundStatus() {
	}

	public FundStatus(String name) {
		this.name = name;
	}

	public FundStatus(String name, String description, Set funds) {
		this.name = name;
		this.description = description;
		this.funds = funds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fundStatus")
	public Set<Fund> getFunds()
	{
		return this.funds;
	}

	public void setFunds(Set<Fund> funds)
	{
		this.funds = funds;
	}

}
