package in.careerscale.apps.ocms.dao.model;

// Generated Jul 7, 2013 10:49:55 AM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NotificationTemplateStatus generated by hbm2java
 */
@Entity
@Table(name = "notification_template_status", catalog = "ocms")
public class NotificationTemplateStatus implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set notificationTemplates = new HashSet(0);

	public NotificationTemplateStatus() {
	}

	public NotificationTemplateStatus(String name, Set notificationTemplates) {
		this.name = name;
		this.notificationTemplates = notificationTemplates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notificationTemplateStatus")
	public Set<NotificationTemplate> getNotificationTemplates()
	{
		return this.notificationTemplates;
	}

	public void setNotificationTemplates(Set<NotificationTemplate> notificationTemplates)
	{
		this.notificationTemplates = notificationTemplates;
	}

}
