package in.careerscale.apps.ocms.dao.model;

// Generated Mar 9, 2013 3:56:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OrgType generated by hbm2java
 */
@Entity
@Table(name = "org_type", catalog = "ocms", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class OrgType implements java.io.Serializable {

	private Integer id;
	private OrgType orgType;
	private String name;
	private String description;
	private Set<OrgType> orgTypes = new HashSet<OrgType>(0);
	private Set<Organization> organizations = new HashSet<Organization>(0);

	public OrgType() {
	}

	public OrgType(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public OrgType(OrgType orgType, String name, String description,
			Set<OrgType> orgTypes, Set<Organization> organizations) {
		this.orgType = orgType;
		this.name = name;
		this.description = description;
		this.orgTypes = orgTypes;
		this.organizations = organizations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	public OrgType getOrgType() {
		return this.orgType;
	}

	public void setOrgType(OrgType orgType) {
		this.orgType = orgType;
	}

	@Column(name = "name", unique = true, nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgType")
	public Set<OrgType> getOrgTypes() {
		return this.orgTypes;
	}

	public void setOrgTypes(Set<OrgType> orgTypes) {
		this.orgTypes = orgTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgType")
	public Set<Organization> getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Set<Organization> organizations) {
		this.organizations = organizations;
	}

}
