package in.careerscale.apps.ocms.dao.model;

// Generated Jun 6, 2011 8:21:35 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile", catalog = "ocms")
public class UserProfile implements java.io.Serializable {

	private Integer id;
	private LoginMaster loginMaster;
	private String otherEmailId;
	private String bloodGroup;
	private Date anniversary;
	private Boolean monthlyUpdates;
	private Boolean specialUpdates;
	private Boolean regularUpdates;

	public UserProfile() {
	}

	public UserProfile(LoginMaster loginMaster, String otherEmailId,
			String bloodGroup, Date anniversary, Boolean monthlyUpdates,
			Boolean specialUpdates,Boolean regularUpdates) {
		this.loginMaster = loginMaster;
		this.otherEmailId = otherEmailId;
		this.bloodGroup = bloodGroup;
		this.anniversary = anniversary;
		this.monthlyUpdates = monthlyUpdates;
		this.specialUpdates = specialUpdates;
		this.regularUpdates = regularUpdates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public LoginMaster getLoginMaster() {
		return this.loginMaster;
	}

	public void setLoginMaster(LoginMaster loginMaster) {
		this.loginMaster = loginMaster;
	}

	@Column(name = "other_email_id", nullable = false, length = 100)
	public String getOtherEmailId() {
		return this.otherEmailId;
	}

	public void setOtherEmailId(String otherEmailId) {
		this.otherEmailId = otherEmailId;
	}

	@Column(name = "blood_group", nullable = false, length = 10)
	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "anniversary", nullable = false, length = 19)
	public Date getAnniversary() {
		return this.anniversary;
	}

	public void setAnniversary(Date anniversary) {
		this.anniversary = anniversary;
	}

	@Column(name = "monthly_updates", nullable = false)
	public Boolean getMonthlyUpdates() {
		return this.monthlyUpdates;
	}

	public void setMonthlyUpdates(Boolean monthlyUpdates) {
		this.monthlyUpdates = monthlyUpdates;
	}

	@Column(name = "special_updates", nullable = false)
	public Boolean getSpecialUpdates() {
		return this.specialUpdates;
	}

	public void setSpecialUpdates(Boolean specialUpdates) {
		this.specialUpdates = specialUpdates;
	}

	@Column(name = "regular_updates", nullable = false)
	public Boolean getRegularUpdates() {
		return regularUpdates;
	}

	public void setRegularUpdates(Boolean regularUpdates) {
		this.regularUpdates = regularUpdates;
	}
	
	

}
