package in.careerscale.apps.ocms.dao.model;

// Generated Jul 7, 2013 10:49:55 AM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CaseStatusMaster generated by hbm2java
 */
@Entity
@Table(name = "case_status_master", catalog = "ocms", uniqueConstraints = @UniqueConstraint(columnNames = "case_status_name"))
public class CaseStatusMaster implements java.io.Serializable {

	private Integer id;
	private String caseStatusName;
	private String caseStatusDescription;
	private Set caseMasters = new HashSet(0);

	public CaseStatusMaster() {
	}

	public CaseStatusMaster(String caseStatusName) {
		this.caseStatusName = caseStatusName;
	}

	public CaseStatusMaster(String caseStatusName,
			String caseStatusDescription, Set caseMasters) {
		this.caseStatusName = caseStatusName;
		this.caseStatusDescription = caseStatusDescription;
		this.caseMasters = caseMasters;
	}

	public CaseStatusMaster(String name, String description)
	{
		this.caseStatusName = name;
		this.caseStatusDescription = description;
	}

	public CaseStatusMaster(Integer id, String name, String description)
	{
		this.id = id;
		this.caseStatusName = name;
		this.caseStatusDescription = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "case_status_name", unique = true, nullable = false, length = 50)
	public String getCaseStatusName() {
		return this.caseStatusName;
	}

	public void setCaseStatusName(String caseStatusName) {
		this.caseStatusName = caseStatusName;
	}

	@Column(name = "case_status_description")
	public String getCaseStatusDescription() {
		return this.caseStatusDescription;
	}

	public void setCaseStatusDescription(String caseStatusDescription) {
		this.caseStatusDescription = caseStatusDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caseStatusMaster")
	public Set<CaseMaster> getCaseMasters()
	{
		return this.caseMasters;
	}

	public void setCaseMasters(Set<CaseMaster> caseMasters)
	{
		this.caseMasters = caseMasters;
	}

}
