package in.careerscale.apps.ocms.dao.model;

// Generated Jun 6, 2011 8:21:35 AM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FundManagement generated by hbm2java
 */
@Entity
@Table(name = "fund_management", catalog = "ocms")
public class FundManagement implements java.io.Serializable {

	private Integer id;
	private CaseMaster caseMaster;
	private String donor;
	private String purpose;
	private int amount;
	private int creditDebit;
	private Date date;

	public FundManagement() {
	}

	public FundManagement(CaseMaster caseMaster, String donor, String purpose,
			int amount, int creditDebit, Date date) {
		this.caseMaster = caseMaster;
		this.donor = donor;
		this.purpose = purpose;
		this.amount = amount;
		this.creditDebit = creditDebit;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_id", nullable = false)
	public CaseMaster getCaseMaster() {
		return this.caseMaster;
	}

	public void setCaseMaster(CaseMaster caseMaster) {
		this.caseMaster = caseMaster;
	}

	@Column(name = "donor", nullable = false, length = 100)
	public String getDonor() {
		return this.donor;
	}

	public void setDonor(String donor) {
		this.donor = donor;
	}

	@Column(name = "purpose", nullable = false)
	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	@Column(name = "amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@Column(name = "credit_debit", nullable = false)
	public int getCreditDebit() {
		return this.creditDebit;
	}

	public void setCreditDebit(int creditDebit) {
		this.creditDebit = creditDebit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
