package in.careerscale.apps.ocms.dao.model;

// Generated Jun 6, 2011 8:21:35 AM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HelpCategory generated by hbm2java
 */
@Entity
@Table(name = "help_category", catalog = "ocms")
public class HelpCategory implements java.io.Serializable {

	private Integer categoryId;
	private String categoryName;
	private String description;
	private Set<CaseMaster> caseMasters = new HashSet<CaseMaster>(0);
	private Set<LoginMaster> loginMasters = new HashSet<LoginMaster>(0);

	public HelpCategory() {
	}

	public HelpCategory(String categoryName) {
		this.categoryName = categoryName;
	}

	public HelpCategory(String categoryName, String description,
			Set<CaseMaster> caseMasters, Set<LoginMaster> loginMasters) {
		this.categoryName = categoryName;
		this.description = description;
		this.caseMasters = caseMasters;
		this.loginMasters = loginMasters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "category_id", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category_name", nullable = false, length = 50)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "helpCategory")
	public Set<CaseMaster> getCaseMasters() {
		return this.caseMasters;
	}

	public void setCaseMasters(Set<CaseMaster> caseMasters) {
		this.caseMasters = caseMasters;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "help_category_user", catalog = "ocms", joinColumns = { @JoinColumn(name = "help_category_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<LoginMaster> getLoginMasters() {
		return this.loginMasters;
	}

	public void setLoginMasters(Set<LoginMaster> loginMasters) {
		this.loginMasters = loginMasters;
	}

}
