package in.careerscale.apps.ocms.dao.model;

// Generated Jul 7, 2013 10:49:55 AM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NotificationTemplate generated by hbm2java
 */
@Entity
@Table(name = "notification_template", catalog = "ocms")
public class NotificationTemplate implements java.io.Serializable {

	private Integer id;
	private NotificationTemplateStatus notificationTemplateStatus;
	private String name;
	private Set notifications = new HashSet(0);
	private Set notificationDetailses = new HashSet(0);

	public NotificationTemplate() {
	}

	public NotificationTemplate(
			NotificationTemplateStatus notificationTemplateStatus) {
		this.notificationTemplateStatus = notificationTemplateStatus;
	}

	public NotificationTemplate(
			NotificationTemplateStatus notificationTemplateStatus, String name,
			Set notifications, Set notificationDetailses) {
		this.notificationTemplateStatus = notificationTemplateStatus;
		this.name = name;
		this.notifications = notifications;
		this.notificationDetailses = notificationDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id", nullable = false)
	public NotificationTemplateStatus getNotificationTemplateStatus() {
		return this.notificationTemplateStatus;
	}

	public void setNotificationTemplateStatus(
			NotificationTemplateStatus notificationTemplateStatus) {
		this.notificationTemplateStatus = notificationTemplateStatus;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notificationTemplate")
	public Set<Notification> getNotifications()
	{
		return this.notifications;
	}

	public void setNotifications(Set<Notification> notifications)
	{
		this.notifications = notifications;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notificationTemplate")
	public Set<NotificationDetails> getNotificationDetailses()
	{
		return this.notificationDetailses;
	}

	public void setNotificationDetailses(Set<NotificationDetails> notificationDetailses)
	{
		this.notificationDetailses = notificationDetailses;
	}

}
