package in.careerscale.apps.ocms.dao.model;

// Generated Jul 7, 2013 10:49:55 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NotificationDetails generated by hbm2java
 */
@Entity
@Table(name = "notification_details", catalog = "ocms")
public class NotificationDetails implements java.io.Serializable {

	private int id;
	private NotificationTemplate notificationTemplate;
	private String notificationType;
	private String templateText;

	public NotificationDetails() {
	}

	public NotificationDetails(int id, String templateText) {
		this.id = id;
		this.templateText = templateText;
	}

	public NotificationDetails(int id,
			NotificationTemplate notificationTemplate, String notificationType,
			String templateText) {
		this.id = id;
		this.notificationTemplate = notificationTemplate;
		this.notificationType = notificationType;
		this.templateText = templateText;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "template_id")
	public NotificationTemplate getNotificationTemplate() {
		return this.notificationTemplate;
	}

	public void setNotificationTemplate(
			NotificationTemplate notificationTemplate) {
		this.notificationTemplate = notificationTemplate;
	}

	@Column(name = "notification_type", length = 45)
	public String getNotificationType() {
		return this.notificationType;
	}

	public void setNotificationType(String notificationType) {
		this.notificationType = notificationType;
	}

	@Column(name = "template_text", nullable = false, length = 65535)
	public String getTemplateText() {
		return this.templateText;
	}

	public void setTemplateText(String templateText) {
		this.templateText = templateText;
	}

}
