package in.careerscale.apps.ocms.dao.model;

// Generated Mar 16, 2013 8:20:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserNetwork generated by hbm2java
 */
@Entity
@Table(name = "user_network", catalog = "ocms")
public class UserNetwork implements java.io.Serializable {

	private String userNetworkId;
	private LoginMaster loginMaster;
	private SocialNetwork socialNetwork;
	private Date lastAccessDate;
	private String userAccessToken;

	public UserNetwork() {
	}

	public UserNetwork(String userNetworkId, LoginMaster loginMaster,
			SocialNetwork socialNetwork,String accessToken) {
		this.userNetworkId = userNetworkId;
		this.loginMaster = loginMaster;
		this.socialNetwork = socialNetwork;
		this.userAccessToken=accessToken;
	}

	public UserNetwork(String userNetworkId, LoginMaster loginMaster,
			SocialNetwork socialNetwork, Date lastAccessDate) {
		this.userNetworkId = userNetworkId;
		this.loginMaster = loginMaster;
		this.socialNetwork = socialNetwork;
		this.lastAccessDate = lastAccessDate;
	}

	@Id
	@Column(name = "user_network_id", unique = true, nullable = false, length = 100)
	public String getUserNetworkId() {
		return this.userNetworkId;
	}

	public void setUserNetworkId(String userNetworkId) {
		this.userNetworkId = userNetworkId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public LoginMaster getLoginMaster() {
		return this.loginMaster;
	}

	public void setLoginMaster(LoginMaster loginMaster) {
		this.loginMaster = loginMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "network_id", nullable = false)
	public SocialNetwork getSocialNetwork() {
		return this.socialNetwork;
	}

	public void setSocialNetwork(SocialNetwork socialNetwork) {
		this.socialNetwork = socialNetwork;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_access_date", length = 0)
	public Date getLastAccessDate() {
		return this.lastAccessDate;
	}

	public void setLastAccessDate(Date lastAccessDate) {
		this.lastAccessDate = lastAccessDate;
	}
	
	@Column(name = "user_access_token",length = 150)
	public String getUserAccessToken() {
		return this.userAccessToken;
	}

	public void setUserAccessToken(String userAccessToken) {
		this.userAccessToken = userAccessToken;
	}

}
