package in.careerscale.apps.ocms.dao.model;

// Generated Mar 16, 2013 8:20:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile", catalog = "ocms")
public class UserProfile implements java.io.Serializable {

	private LoginMaster loginMaster;
	private String otherEmailId;
	private String bloodGroup;
	private Date anniversary;
	private boolean monthlyUpdates;
	private boolean specialUpdates;
	private boolean regularUpdates;

	private String mobileNumber1;
	private String mobileNumber2;
	private String landlineNumber;

	private Address address;

	public UserProfile() {
	}

	public UserProfile(LoginMaster loginMaster, String otherEmailId,
			String bloodGroup, Date anniversary, boolean monthlyUpdates,
			boolean specialUpdates, boolean regularUpdates) {
		this.loginMaster = loginMaster;
		this.otherEmailId = otherEmailId;
		this.bloodGroup = bloodGroup;
		this.anniversary = anniversary;
		this.monthlyUpdates = monthlyUpdates;
		this.specialUpdates = specialUpdates;
		this.regularUpdates = regularUpdates;
	}

	@Id
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id", nullable = false)
	public LoginMaster getLoginMaster() {
		return this.loginMaster;
	}

	public void setLoginMaster(LoginMaster loginMaster) {
		this.loginMaster = loginMaster;
	}

	@Column(name = "other_email_id", nullable = false, length = 100)
	public String getOtherEmailId() {
		return this.otherEmailId;
	}

	public void setOtherEmailId(String otherEmailId) {
		this.otherEmailId = otherEmailId;
	}

	@Column(name = "blood_group", nullable = false, length = 10)
	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "anniversary", nullable = false, length = 0)
	public Date getAnniversary() {
		return this.anniversary;
	}

	public void setAnniversary(Date anniversary) {
		this.anniversary = anniversary;
	}

	@Column(name = "monthly_updates", nullable = false)
	public boolean isMonthlyUpdates() {
		return this.monthlyUpdates;
	}

	public void setMonthlyUpdates(boolean monthlyUpdates) {
		this.monthlyUpdates = monthlyUpdates;
	}

	@Column(name = "special_updates", nullable = false)
	public boolean isSpecialUpdates() {
		return this.specialUpdates;
	}

	public void setSpecialUpdates(boolean specialUpdates) {
		this.specialUpdates = specialUpdates;
	}

	@Column(name = "regular_updates", nullable = false)
	public boolean isRegularUpdates() {
		return this.regularUpdates;
	}

	public void setRegularUpdates(boolean regularUpdates) {
		this.regularUpdates = regularUpdates;
	}

	@Column(name = "mobile_number1", nullable = false, length = 20)
	public String getMobileNumber1()
	{
		return mobileNumber1;
	}

	public void setMobileNumber1(String mobileNumber1)
	{
		this.mobileNumber1 = mobileNumber1;
	}

	public String getMobileNumber2()
	{
		return mobileNumber2;
	}

	@Column(name = "mobile_number2", nullable = false, length = 20)
	public void setMobileNumber2(String mobileNumber2)
	{
		this.mobileNumber2 = mobileNumber2;
	}

	@Column(name = "landline_number", nullable = false, length = 20)
	public String getLandlineNumber()
	{
		return landlineNumber;
	}

	public void setLandlineNumber(String landlineNumber)
	{
		this.landlineNumber = landlineNumber;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "address_id")
	public Address getAddress()
	{
		return this.address;
	}

	public void setAddress(Address address)
	{
		this.address = address;
	}
}
