package in.careerscale.apps.rms.model;

// Generated Jun 23, 2013 2:58:51 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobApplications generated by hbm2java
 */
@Entity
@Table(name = "job_applications", catalog = "rms")
public class JobApplications implements java.io.Serializable {

	private Integer id;
	private Employee employee;
	private JobPosting jobPosting;
	private Vendor vendor;
	private Date applicationDate;
	private String status;
	private String description;
	private String resumeText;

	public JobApplications() {
	}

	public JobApplications(Employee employee, JobPosting jobPosting,
			Vendor vendor, Date applicationDate, String status,
			String description, String resumeText) {
		this.employee = employee;
		this.jobPosting = jobPosting;
		this.vendor = vendor;
		this.applicationDate = applicationDate;
		this.status = status;
		this.description = description;
		this.resumeText = resumeText;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "referral_id")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_id")
	public JobPosting getJobPosting() {
		return this.jobPosting;
	}

	public void setJobPosting(JobPosting jobPosting) {
		this.jobPosting = jobPosting;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendor_id")
	public Vendor getVendor() {
		return this.vendor;
	}

	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "application_date", length = 19)
	public Date getApplicationDate() {
		return this.applicationDate;
	}

	public void setApplicationDate(Date applicationDate) {
		this.applicationDate = applicationDate;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "resume_text", length = 16777215)
	public String getResumeText() {
		return this.resumeText;
	}

	public void setResumeText(String resumeText) {
		this.resumeText = resumeText;
	}

}
