package in.careerscale.apps.ocms.model;

// Generated Jun 6, 2011 8:21:35 AM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CaseType generated by hbm2java
 */
@Entity
@Table(name = "case_type", catalog = "ocms")
public class CaseType implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<CaseSubType> caseSubTypes = new HashSet<CaseSubType>(0);

	public CaseType() {
	}

	public CaseType(String name) {
		this.name = name;
	}

	public CaseType(String name, String description,
			Set<CaseSubType> caseSubTypes) {
		this.name = name;
		this.description = description;
		this.caseSubTypes = caseSubTypes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caseType")
	public Set<CaseSubType> getCaseSubTypes() {
		return this.caseSubTypes;
	}

	public void setCaseSubTypes(Set<CaseSubType> caseSubTypes) {
		this.caseSubTypes = caseSubTypes;
	}

}
