package in.careerscale.apps.ocms.model;

// Generated Jun 6, 2011 8:21:35 AM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolePermission generated by hbm2java
 */
@Entity
@Table(name = "role_permission", catalog = "ocms")
public class RolePermission implements java.io.Serializable {

	private Integer id;
	private RoleMaster roleMaster;
	private String name;
	private String readPerm;
	private String editPerm;
	private String addPerm;
	private String approvePerm;
	private String deletePerm;
	private String description;

	public RolePermission() {
	}

	public RolePermission(String name, String readPerm, String editPerm,
			String addPerm, String approvePerm, String deletePerm,
			String description) {
		this.name = name;
		this.readPerm = readPerm;
		this.editPerm = editPerm;
		this.addPerm = addPerm;
		this.approvePerm = approvePerm;
		this.deletePerm = deletePerm;
		this.description = description;
	}

	public RolePermission(RoleMaster roleMaster, String name, String readPerm,
			String editPerm, String addPerm, String approvePerm,
			String deletePerm, String description) {
		this.roleMaster = roleMaster;
		this.name = name;
		this.readPerm = readPerm;
		this.editPerm = editPerm;
		this.addPerm = addPerm;
		this.approvePerm = approvePerm;
		this.deletePerm = deletePerm;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public RoleMaster getRoleMaster() {
		return this.roleMaster;
	}

	public void setRoleMaster(RoleMaster roleMaster) {
		this.roleMaster = roleMaster;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "read_perm", nullable = false, length = 1)
	public String getReadPerm() {
		return this.readPerm;
	}

	public void setReadPerm(String readPerm) {
		this.readPerm = readPerm;
	}

	@Column(name = "edit_perm", nullable = false, length = 1)
	public String getEditPerm() {
		return this.editPerm;
	}

	public void setEditPerm(String editPerm) {
		this.editPerm = editPerm;
	}

	@Column(name = "add_perm", nullable = false, length = 1)
	public String getAddPerm() {
		return this.addPerm;
	}

	public void setAddPerm(String addPerm) {
		this.addPerm = addPerm;
	}

	@Column(name = "approve_perm", nullable = false, length = 1)
	public String getApprovePerm() {
		return this.approvePerm;
	}

	public void setApprovePerm(String approvePerm) {
		this.approvePerm = approvePerm;
	}

	@Column(name = "delete_perm", nullable = false, length = 1)
	public String getDeletePerm() {
		return this.deletePerm;
	}

	public void setDeletePerm(String deletePerm) {
		this.deletePerm = deletePerm;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
